export const datamock = {
  cases_time_series: [
    {
      dailyconfirmed: '1',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '30 January ',
      totalconfirmed: '1',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '31 January ',
      totalconfirmed: '1',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '01 February ',
      totalconfirmed: '1',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '1',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '02 February ',
      totalconfirmed: '2',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '1',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '03 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '04 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '05 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '06 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '07 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '08 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '09 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '10 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '11 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '12 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '0',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '1',
      date: '13 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '1',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '14 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '1',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '15 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '1',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '1',
      date: '16 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '2',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '17 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '2',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '18 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '2',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '19 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '2',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '1',
      date: '20 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '21 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '22 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '23 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '24 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '25 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '26 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '27 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '28 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '29 February ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '0',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '01 March ',
      totalconfirmed: '3',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '2',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '02 March ',
      totalconfirmed: '5',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '1',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '03 March ',
      totalconfirmed: '6',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '22',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '04 March ',
      totalconfirmed: '28',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '2',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '05 March ',
      totalconfirmed: '30',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '1',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '06 March ',
      totalconfirmed: '31',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '3',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '07 March ',
      totalconfirmed: '34',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '5',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '08 March ',
      totalconfirmed: '39',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '9',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '09 March ',
      totalconfirmed: '48',
      totaldeceased: '0',
      totalrecovered: '3',
    },
    {
      dailyconfirmed: '15',
      dailydeceased: '0',
      dailyrecovered: '1',
      date: '10 March ',
      totalconfirmed: '63',
      totaldeceased: '0',
      totalrecovered: '4',
    },
    {
      dailyconfirmed: '7',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '11 March ',
      totalconfirmed: '70',
      totaldeceased: '0',
      totalrecovered: '4',
    },
    {
      dailyconfirmed: '12',
      dailydeceased: '1',
      dailyrecovered: '0',
      date: '12 March ',
      totalconfirmed: '82',
      totaldeceased: '1',
      totalrecovered: '4',
    },
    {
      dailyconfirmed: '9',
      dailydeceased: '0',
      dailyrecovered: '6',
      date: '13 March ',
      totalconfirmed: '91',
      totaldeceased: '1',
      totalrecovered: '10',
    },
    {
      dailyconfirmed: '16',
      dailydeceased: '1',
      dailyrecovered: '0',
      date: '14 March ',
      totalconfirmed: '107',
      totaldeceased: '2',
      totalrecovered: '10',
    },
    {
      dailyconfirmed: '5',
      dailydeceased: '0',
      dailyrecovered: '3',
      date: '15 March ',
      totalconfirmed: '112',
      totaldeceased: '2',
      totalrecovered: '13',
    },
    {
      dailyconfirmed: '15',
      dailydeceased: '0',
      dailyrecovered: '1',
      date: '16 March ',
      totalconfirmed: '127',
      totaldeceased: '2',
      totalrecovered: '14',
    },
    {
      dailyconfirmed: '19',
      dailydeceased: '1',
      dailyrecovered: '1',
      date: '17 March ',
      totalconfirmed: '146',
      totaldeceased: '3',
      totalrecovered: '15',
    },
    {
      dailyconfirmed: '25',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '18 March ',
      totalconfirmed: '171',
      totaldeceased: '3',
      totalrecovered: '15',
    },
    {
      dailyconfirmed: '27',
      dailydeceased: '1',
      dailyrecovered: '5',
      date: '19 March ',
      totalconfirmed: '198',
      totaldeceased: '4',
      totalrecovered: '20',
    },
    {
      dailyconfirmed: '60',
      dailydeceased: '0',
      dailyrecovered: '3',
      date: '20 March ',
      totalconfirmed: '258',
      totaldeceased: '4',
      totalrecovered: '23',
    },
    {
      dailyconfirmed: '76',
      dailydeceased: '0',
      dailyrecovered: '0',
      date: '21 March ',
      totalconfirmed: '334',
      totaldeceased: '4',
      totalrecovered: '23',
    },
    {
      dailyconfirmed: '69',
      dailydeceased: '3',
      dailyrecovered: '0',
      date: '22 March ',
      totalconfirmed: '403',
      totaldeceased: '7',
      totalrecovered: '23',
    },
    {
      dailyconfirmed: '94',
      dailydeceased: '2',
      dailyrecovered: '2',
      date: '23 March ',
      totalconfirmed: '497',
      totaldeceased: '9',
      totalrecovered: '25',
    },
    {
      dailyconfirmed: '74',
      dailydeceased: '1',
      dailyrecovered: '15',
      date: '24 March ',
      totalconfirmed: '571',
      totaldeceased: '10',
      totalrecovered: '40',
    },
    {
      dailyconfirmed: '86',
      dailydeceased: '1',
      dailyrecovered: '3',
      date: '25 March ',
      totalconfirmed: '657',
      totaldeceased: '11',
      totalrecovered: '43',
    },
    {
      dailyconfirmed: '73',
      dailydeceased: '5',
      dailyrecovered: '7',
      date: '26 March ',
      totalconfirmed: '730',
      totaldeceased: '16',
      totalrecovered: '50',
    },
    {
      dailyconfirmed: '153',
      dailydeceased: '3',
      dailyrecovered: '25',
      date: '27 March ',
      totalconfirmed: '883',
      totaldeceased: '19',
      totalrecovered: '75',
    },
    {
      dailyconfirmed: '141',
      dailydeceased: '5',
      dailyrecovered: '10',
      date: '28 March ',
      totalconfirmed: '1024',
      totaldeceased: '24',
      totalrecovered: '85',
    },
    {
      dailyconfirmed: '115',
      dailydeceased: '3',
      dailyrecovered: '17',
      date: '29 March ',
      totalconfirmed: '1139',
      totaldeceased: '27',
      totalrecovered: '102',
    },
    {
      dailyconfirmed: '190',
      dailydeceased: '16',
      dailyrecovered: '35',
      date: '30 March ',
      totalconfirmed: '1329',
      totaldeceased: '43',
      totalrecovered: '137',
    },
    {
      dailyconfirmed: '306',
      dailydeceased: '6',
      dailyrecovered: '13',
      date: '31 March ',
      totalconfirmed: '1635',
      totaldeceased: '49',
      totalrecovered: '150',
    },
    {
      dailyconfirmed: '424',
      dailydeceased: '7',
      dailyrecovered: '19',
      date: '01 April ',
      totalconfirmed: '2059',
      totaldeceased: '56',
      totalrecovered: '169',
    },
    {
      dailyconfirmed: '486',
      dailydeceased: '16',
      dailyrecovered: '22',
      date: '02 April ',
      totalconfirmed: '2545',
      totaldeceased: '72',
      totalrecovered: '191',
    },
    {
      dailyconfirmed: '560',
      dailydeceased: '14',
      dailyrecovered: '39',
      date: '03 April ',
      totalconfirmed: '3105',
      totaldeceased: '86',
      totalrecovered: '230',
    },
    {
      dailyconfirmed: '579',
      dailydeceased: '13',
      dailyrecovered: '56',
      date: '04 April ',
      totalconfirmed: '3684',
      totaldeceased: '99',
      totalrecovered: '286',
    },
    {
      dailyconfirmed: '605',
      dailydeceased: '22',
      dailyrecovered: '43',
      date: '05 April ',
      totalconfirmed: '4289',
      totaldeceased: '121',
      totalrecovered: '329',
    },
    {
      dailyconfirmed: '489',
      dailydeceased: '16',
      dailyrecovered: '65',
      date: '06 April ',
      totalconfirmed: '4778',
      totaldeceased: '137',
      totalrecovered: '394',
    },
    {
      dailyconfirmed: '573',
      dailydeceased: '26',
      dailyrecovered: '75',
      date: '07 April ',
      totalconfirmed: '5351',
      totaldeceased: '163',
      totalrecovered: '469',
    },
    {
      dailyconfirmed: '565',
      dailydeceased: '20',
      dailyrecovered: '96',
      date: '08 April ',
      totalconfirmed: '5916',
      totaldeceased: '183',
      totalrecovered: '565',
    },
  ],
  statewise: [
    {
      active: '5623',
      confirmed: '6399',
      deaths: '186',
      deltaconfirmed: '483',
      deltadeaths: '6',
      deltarecovered: '25',
      lastupdatedtime: '09/04/2020 18:30:24',
      recovered: '590',
      state: 'Total',
      statecode: 'TT',
    },
    {
      active: '1108',
      confirmed: '1297',
      deaths: '72',
      deltaconfirmed: '162',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 12:06:14',
      recovered: '117',
      state: 'Maharashtra',
      statecode: 'MH',
    },
    {
      active: '799',
      confirmed: '834',
      deaths: '8',
      deltaconfirmed: '96',
      deltadeaths: '0',
      deltarecovered: '6',
      lastupdatedtime: '09/04/2020 18:30:27',
      recovered: '27',
      state: 'Tamil Nadu',
      statecode: 'TN',
    },
    {
      active: '639',
      confirmed: '669',
      deaths: '9',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 22:20:32',
      recovered: '21',
      state: 'Delhi',
      statecode: 'DL',
    },
    {
      active: '397',
      confirmed: '453',
      deaths: '11',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 19:00:25',
      recovered: '45',
      state: 'Telangana',
      statecode: 'TG',
    },
    {
      active: '382',
      confirmed: '430',
      deaths: '3',
      deltaconfirmed: '47',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 15:05:34',
      recovered: '45',
      state: 'Rajasthan',
      statecode: 'RJ',
    },
    {
      active: '258',
      confirmed: '357',
      deaths: '2',
      deltaconfirmed: '12',
      deltadeaths: '0',
      deltarecovered: '13',
      lastupdatedtime: '09/04/2020 18:10:35',
      recovered: '97',
      state: 'Kerala',
      statecode: 'KL',
    },
    {
      active: '326',
      confirmed: '361',
      deaths: '4',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 19:15:28',
      recovered: '31',
      state: 'Uttar Pradesh',
      statecode: 'UP',
    },
    {
      active: '339',
      confirmed: '348',
      deaths: '3',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 14:40:25',
      recovered: '6',
      state: 'Andhra Pradesh',
      statecode: 'AP',
    },
    {
      active: '296',
      confirmed: '347',
      deaths: '26',
      deltaconfirmed: '6',
      deltadeaths: '2',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 16:35:26',
      recovered: '25',
      state: 'Madhya Pradesh',
      statecode: 'MP',
    },
    {
      active: '161',
      confirmed: '197',
      deaths: '6',
      deltaconfirmed: '16',
      deltadeaths: '1',
      deltarecovered: '2',
      lastupdatedtime: '09/04/2020 17:35:25',
      recovered: '30',
      state: 'Karnataka',
      statecode: 'KA',
    },
    {
      active: '198',
      confirmed: '241',
      deaths: '17',
      deltaconfirmed: '55',
      deltadeaths: '1',
      deltarecovered: '1',
      lastupdatedtime: '09/04/2020 11:56:11',
      recovered: '26',
      state: 'Gujarat',
      statecode: 'GJ',
    },
    {
      active: '136',
      confirmed: '170',
      deaths: '2',
      deltaconfirmed: '3',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 12:51:40',
      recovered: '32',
      state: 'Haryana',
      statecode: 'HR',
    },
    {
      active: '175',
      confirmed: '184',
      deaths: '3',
      deltaconfirmed: '26',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 16:56:28',
      recovered: '6',
      state: 'Jammu and Kashmir',
      statecode: 'JK',
    },
    {
      active: '106',
      confirmed: '130',
      deaths: '10',
      deltaconfirmed: '24',
      deltadeaths: '1',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 15:05:38',
      recovered: '14',
      state: 'Punjab',
      statecode: 'PB',
    },
    {
      active: '82',
      confirmed: '103',
      deaths: '5',
      deltaconfirmed: '4',
      deltadeaths: '0',
      deltarecovered: '3',
      lastupdatedtime: '09/04/2020 10:17:04',
      recovered: '16',
      state: 'West Bengal',
      statecode: 'WB',
    },
    {
      active: '41',
      confirmed: '44',
      deaths: '1',
      deltaconfirmed: '2',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 12:52:24',
      recovered: '2',
      state: 'Odisha',
      statecode: 'OR',
    },
    {
      active: '35',
      confirmed: '51',
      deaths: '1',
      deltaconfirmed: '12',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 12:06:17',
      recovered: '15',
      state: 'Bihar',
      statecode: 'BR',
    },
    {
      active: '30',
      confirmed: '35',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 21:20:26',
      recovered: '5',
      state: 'Uttarakhand',
      statecode: 'UT',
    },
    {
      active: '28',
      confirmed: '28',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '08/04/2020 00:04:27',
      recovered: '0',
      state: 'Assam',
      statecode: 'AS',
    },
    {
      active: '11',
      confirmed: '18',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '07/04/2020 22:35:25',
      recovered: '7',
      state: 'Chandigarh',
      statecode: 'CH',
    },
    {
      active: '24',
      confirmed: '28',
      deaths: '2',
      deltaconfirmed: '1',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 10:50:40',
      recovered: '2',
      state: 'Himachal Pradesh',
      statecode: 'HP',
    },
    {
      active: '4',
      confirmed: '14',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '06/04/2020 23:56:56',
      recovered: '10',
      state: 'Ladakh',
      statecode: 'LA',
    },
    {
      active: '11',
      confirmed: '11',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '30/03/2020 11:27:27',
      recovered: '0',
      state: 'Andaman and Nicobar Islands',
      statecode: 'AN',
    },
    {
      active: '9',
      confirmed: '18',
      deaths: '0',
      deltaconfirmed: '8',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 10:50:42',
      recovered: '9',
      state: 'Chhattisgarh',
      statecode: 'CT',
    },
    {
      active: '7',
      confirmed: '7',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '04/04/2020 09:42:27',
      recovered: '0',
      state: 'Goa',
      statecode: 'GA',
    },
    {
      active: '4',
      confirmed: '5',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '07/04/2020 17:24:56',
      recovered: '1',
      state: 'Puducherry',
      statecode: 'PY',
    },
    {
      active: '12',
      confirmed: '13',
      deaths: '1',
      deltaconfirmed: '9',
      deltadeaths: '1',
      deltarecovered: '0',
      lastupdatedtime: '09/04/2020 10:50:43',
      recovered: '0',
      state: 'Jharkhand',
      statecode: 'JH',
    },
    {
      active: '1',
      confirmed: '2',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '06/04/2020 22:35:54',
      recovered: '1',
      state: 'Manipur',
      statecode: 'MN',
    },
    {
      active: '1',
      confirmed: '1',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Mizoram',
      statecode: 'MZ',
    },
    {
      active: '1',
      confirmed: '1',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '02/04/2020 11:42:31',
      recovered: '0',
      state: 'Arunachal Pradesh',
      statecode: 'AR',
    },
    {
      active: '1',
      confirmed: '1',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '06/04/2020 15:22:25',
      recovered: '0',
      state: 'Dadra and Nagar Haveli',
      statecode: 'DN',
    },
    {
      active: '1',
      confirmed: '1',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '06/04/2020 22:14:41',
      recovered: '0',
      state: 'Tripura',
      statecode: 'TR',
    },
    {
      active: '0',
      confirmed: '0',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Daman and Diu',
      statecode: 'DD',
    },
    {
      active: '0',
      confirmed: '0',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Lakshadweep',
      statecode: 'LD',
    },
    {
      active: '0',
      confirmed: '0',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Meghalaya',
      statecode: 'ML',
    },
    {
      active: '0',
      confirmed: '0',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Nagaland',
      statecode: 'NL',
    },
    {
      active: '0',
      confirmed: '0',
      deaths: '0',
      deltaconfirmed: '0',
      deltadeaths: '0',
      deltarecovered: '0',
      lastupdatedtime: '26/03/2020 07:19:29',
      recovered: '0',
      state: 'Sikkim',
      statecode: 'SK',
    },
  ],
  tested: [
    {
      _cyevm: '600',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'Press_Release_ICMR_13March2020.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '5900',
      totalpositivecases: '78',
      totalsamplestested: '6500',
      updatetimestamp: '13/03/2020 12:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_18March_6PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '12235',
      totalpositivecases: '150',
      totalsamplestested: '13125',
      updatetimestamp: '18/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_19March_10AM_IST_V2.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '12426',
      totalpositivecases: '168',
      totalsamplestested: '13316',
      updatetimestamp: '19/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_19March_6PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '13285',
      totalpositivecases: '182',
      totalsamplestested: '14175',
      updatetimestamp: '19/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_20March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '13486',
      totalpositivecases: '206',
      totalsamplestested: '14376',
      updatetimestamp: '20/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_20March_6PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '14514',
      totalpositivecases: '236',
      totalsamplestested: '15404',
      updatetimestamp: '20/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_21March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '14811',
      totalpositivecases: '271',
      totalsamplestested: '15701',
      updatetimestamp: '21/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_21March_6PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '16021',
      totalpositivecases: '315',
      totalsamplestested: '16911',
      updatetimestamp: '21/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_22March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '16109',
      totalpositivecases: '341',
      totalsamplestested: '16999',
      updatetimestamp: '22/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_22March_6PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '17237',
      totalpositivecases: '396',
      totalsamplestested: '18127',
      updatetimestamp: '22/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_23March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '17493',
      totalpositivecases: '415',
      totalsamplestested: '18383',
      updatetimestamp: '23/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_23March_8PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '19817',
      totalpositivecases: '471',
      totalsamplestested: '20707',
      updatetimestamp: '23/03/2020 08:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_24March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '19974',
      totalpositivecases: '482',
      totalsamplestested: '20864',
      updatetimestamp: '24/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_24March_8PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '21804',
      totalpositivecases: '536',
      totalsamplestested: '22694',
      updatetimestamp: '24/03/2020 08:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_25March_10AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '22038',
      totalpositivecases: '539',
      totalsamplestested: '22928',
      updatetimestamp: '25/03/2020 10:00: am',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_25March_8PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '24254',
      totalpositivecases: '581',
      totalsamplestested: '25144',
      updatetimestamp: '25/03/2020 08:00: pm',
    },
    {
      _cyevm: '0',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: '',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '',
      totalsamplestested: '',
      updatetimestamp: '26/03/2020 10:00: am',
    },
    {
      _cyevm: '0',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: '',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '',
      totalsamplestested: '',
      updatetimestamp: '26/03/2020 06:00: pm',
    },
    {
      _cyevm: '890',
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_website_update_27March_9AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '26798',
      totalpositivecases: '691',
      totalsamplestested: '27688',
      updatetimestamp: '27/03/2020 09:00: am',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'MoH Press conference with Dr. Raman G',
      testsconductedbyprivatelabs: '1334',
      totalindividualstested: '',
      totalpositivecases: '',
      totalsamplestested: '38442',
      updatetimestamp: '30/03/2020 12:00: am',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'MoH Press conference with Dr. Raman G',
      testsconductedbyprivatelabs: '1733',
      totalindividualstested: '',
      totalpositivecases: '',
      totalsamplestested: '42788',
      updatetimestamp: '31/03/2020 12:00: am',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'https://twitter.com/PTI_News/status/1245308976440340482',
      testsconductedbyprivatelabs: '4562',
      totalindividualstested: '',
      totalpositivecases: '1637',
      totalsamplestested: '47951',
      updatetimestamp: '01/04/2020 12:00: am',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_testing_update_02April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '2056',
      totalsamplestested: '55851',
      updatetimestamp: '02/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source: 'ICMR_testing_update_03April_9AM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '2183',
      totalsamplestested: '56680',
      updatetimestamp: '03/04/2020 09:00: am',
    },
    {
      positivecasesfromsamplesreported: '575',
      samplereportedtoday: '10034',
      source: 'ICMR_testing_update_03April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '2653',
      totalsamplestested: '69245',
      updatetimestamp: '03/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '',
      samplereportedtoday: '',
      source:
        'https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_04April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '3113',
      totalsamplestested: '79950',
      updatetimestamp: '04/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '295',
      samplereportedtoday: '9369',
      source:
        'https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_05April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '3554',
      totalsamplestested: '89534',
      updatetimestamp: '05/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '311',
      samplereportedtoday: '11432',
      source:
        'https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_06April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '4135',
      totalsamplestested: '101068',
      updatetimestamp: '06/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '285',
      samplereportedtoday: '12584',
      source: 'ICMR_testing_update_07April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '4616',
      totalsamplestested: '114015',
      updatetimestamp: '07/04/2020 09:00: pm',
    },
    {
      positivecasesfromsamplesreported: '320',
      samplereportedtoday: '13143',
      source:
        'https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_08April_9PM_IST.pdf',
      testsconductedbyprivatelabs: '',
      totalindividualstested: '',
      totalpositivecases: '5114',
      totalsamplestested: '127919',
      updatetimestamp: '08/04/2020 09:00: pm',
    },
  ],
};
